Repository pastas/pastas, pull requests merged in 2019-08, with the labels that each got.

#129 Add WellModel
  examples/example_WellModel.py
  examples/notebooks/11_WellModel.ipynb
  examples/notebooks/3_response_functions.ipynb
  pastas/__init__.py
  pastas/model.py
  pastas/rfunc.py
  pastas/stressmodels.py
  pastas/timeseries.py
Labels: development

#138 Solver
  pastas/__init__.py
  pastas/model.py
  pastas/noisemodels.py
  pastas/recharge/recharge_func.py
  pastas/rfunc.py
  pastas/solver.py
  pastas/stressmodels.py
  tests/test_solvers.py
Labels: bug, development, enhancement

#144 improve solve_models() with tmin/tmax options
  pastas/project/project.py
Labels: enhancement
