Repository pastas/pastas, pull requests merged in 2020-07, with the labels that each got.

#208 CONTRIBUTING.md: point to the current dev site
  CONTRIBUTING.md
Labels: enhancement

#220 fix name of series in TimeSeries and name of HantushOld rfunc
  pastas/rfunc.py
  pastas/timeseries.py
Labels: bug

#218 Add Portmanteau test
  pastas/stats/__init__.py
  pastas/stats/tests.py
  tests/test_stats.py
Labels: development

#223 Diagnostics
  doc/api/statistics.rst
  doc/examples/004_diagnostic_checking.ipynb.nblink
  examples/notebooks/4_diagnostic_checking.ipynb
  pastas/modelstats.py
  pastas/plots.py
  pastas/stats/__init__.py
  pastas/stats/core.py
  pastas/stats/dutch.py
  pastas/stats/metrics.py
  pastas/stats/tests.py
  tests/test_stats.py
Labels: development, enhancement

#227 Dinoloket read method
  examples/data/B49F0555001_1.csv
  examples/data/P43H0001.csv
  examples/notebooks/16_reading_dutch_datasets.ipynb
  pastas/__init__.py
  pastas/read/__init__.py
  pastas/read/dinoloket.py
  tests/data/P43H0001.csv
  tests/test_reads.py
Labels: development
