Repository pastas/pastas, pull requests merged in 2022-03, with the labels that each got.

#372 Add Groundwater Signatures Module
  examples/notebooks/21_signatures.ipynb
  pastas/stats/__init__.py
  pastas/stats/signatures.py
  tests/test_signatures.py
Labels: development

#381 Improve fit report
  pastas/model.py
Labels: enhancement

#382 fix #380, modification for #177
  pastas/rfunc.py
  pastas/stressmodels.py
Labels: enhancement

#373 Recharge Model Features - Peterson & Western / Flex (Groundwater Uptake)
  examples/notebooks/07_non_linear_recharge.ipynb
  pastas/read/knmi.py
  pastas/recharge.py
  tests/test_recharge.py
Labels: enhancement, development
