Repository pastas/pastas, pull requests merged in 2023-03, with the labels that each got.

#566 Codacy coverage upload, auto-assign pr and flake8 update
  .github/workflows/auto-author-assign.yml
  .github/workflows/ci.yml
  doc/index.rst
  pyproject.toml
Labels: code quality

#558 add fill/bfill timeseries settings options
  pastas/timeseries.py
Labels: development

#581 Add (Pandas) resample wrapper function to timeseries_utils
  doc/examples/prepare_timeseries.ipynb
  pastas/timeseries.py
  pastas/timeseries_utils.py
Labels: enhancement
