Repository pastas/pastas, pull requests merged in 2023-08, with the labels that each got.

#572 Add MCMC solver to Pastas
  doc/api/index.rst
  doc/examples/uncertainty_emcee.ipynb
  pastas/__init__.py
  pastas/model.py
  pastas/noisemodels.py
  pastas/objective_functions.py
  pastas/recharge.py
  pastas/rfunc.py
  pastas/solver.py
  pastas/stressmodels.py
  pastas/transform.py
  pyproject.toml
  tests/test_solvers.py
Labels: development

#616 Fix issue #536 return true if series are valid, else raise error
  pastas/timeseries.py
Labels: enhancement

#604 silence HantushWellModel info msg about r=1.0
  pastas/model.py
  pastas/modelcompare.py
  pastas/modelplots.py
  pastas/rfunc.py
Labels: bug

#615 Fix issue 608
  doc/conf.py
  doc/examples/index.rst
  pyproject.toml
Labels: documentation
