Repository pastas/pastas, pull requests merged in 2023-02, with the labels that each got.

#520 Fix bug #510
  pastas/timeseries.py
Labels: bug

#521 Update metrics.py
  pastas/stats/metrics.py
Labels: enhancement

#524 fix docstrings and unused code in acf
  pastas/stats/core.py
Labels: enhancement, Documentation

#523 522 fix some bugs in time series and make more efficient
  pastas/timeseries.py
Labels: bug, enhancement

#557 Fix datetime axes with pandas.Timestamp and some other improvements
  doc/examples/03_calibration_options.ipynb
  doc/examples/08_changing_responses.ipynb
  doc/examples/15_timestep_analysis.ipynb
  doc/examples/18_sgi_example.ipynb
  pastas/modelcompare.py
  pastas/modelplots.py
  pastas/modelstats.py
  pastas/plots.py
  pastas/recharge.py
  pastas/stressmodels.py
  pastas/timer.py
Labels: bug

#561 Make table in pastas.plots.series() optional
  doc/examples/03_calibration_options.ipynb
  pastas/plots.py
Labels: enhancement

#553 Update types.py to support Matplotlib <v3.4
  doc/examples/example_uncertainty.py
  pastas/stats/metrics.py
  pastas/typing/__init__.py
  pastas/typing/types.py
  tests/test_model.py
Labels: bug

#560 Improve documentation
  README.rst
  doc/about/01_history.rst
  doc/about/citing.rst
  doc/about/courses.rst
  doc/about/history.rst
  doc/about/index.rst
  doc/about/publications.rst
  doc/about/references.rst
  doc/about/related.rst
  doc/about/team.rst
  doc/developers/index.rst
  doc/examples/adding_rivers.ipynb
  doc/examples/adding_trends.ipynb
  doc/examples/adding_wells.ipynb
  doc/examples/basic_model.ipynb
  doc/examples/calibration_options.ipynb
  doc/examples/changing_responses.ipynb
  doc/examples/comparing_models.ipynb
  doc/examples/diagnostic_checking.ipynb
  doc/examples/fix_parameters.ipynb
  doc/examples/index.rst
  doc/examples/multiple_wells.ipynb
  doc/examples/non_linear_recharge.ipynb
  doc/examples/prepare_timeseries.ipynb
  doc/examples/recharge_estimation.ipynb
  doc/examples/signatures.ipynb
  doc/examples/snowmodel.ipynb
  doc/examples/standardized_groundwater_index.ipynb
  doc/examples/threshold_non_linear.ipynb
  doc/examples/timestep_analysis.ipynb
  doc/examples/uncertainty.ipynb
  doc/examples/uncertainty_emcee.ipynb
  doc/index.rst
  tests/test_notebooks.py
Labels: documentation

#556 Improve modeling with non-daily timesteps
  doc/conf.py
  doc/examples/comparing_models.ipynb
  doc/examples/data/vlissingen_evap_hourly.csv
  doc/examples/data/vlissingen_prec_hourly.csv
  doc/examples/index.rst
  doc/examples/modeling_timestep.ipynb
  pastas/model.py
  pastas/modelcompare.py
  pastas/modelplots.py
  pastas/stats/core.py
  pastas/stats/metrics.py
  pastas/timeseries.py
  pastas/timeseries_utils.py
  tests/test_model.py
Labels: enhancement
