Repository pastas/pastas, pull requests merged in 2023-11, with the labels that each got.

#651 Add Experimental Python 3.12 Testing
  .github/workflows/ci.yml
  pyproject.toml
Labels: code quality

#655 fix for #654
  pastas/stressmodels.py
Labels: enhancement, documentation, priority 1

#656 Improve `ml.plots.stack_results()`
  doc/examples/multiple_wells.ipynb
  pastas/modelplots.py
Labels: enhancement

#662 Update README.rst to fix Codacy links
  README.rst
Labels: bug, priority 0, code quality

#661 add 'norm' attribute to NoiseModelBase
  pastas/noisemodels.py
  tests/test_model.py
Labels: bug

#649 Implement freq_obs for sampling observations prior to optimization
  doc/examples/example_freq_obs.py
  pastas/model.py
Labels: development

#641 Add Plotly plots and extension registration
  doc/api/index.rst
  doc/examples/adding_rivers.ipynb
  doc/examples/adding_wells.ipynb
  doc/examples/changing_responses.ipynb
  doc/examples/plotly_interactive_plots.ipynb
  doc/examples/standardized_groundwater_index.ipynb
  doc/examples/uncertainty_emcee.ipynb
  doc/userguide/stressmodels.ipynb
  pastas/__init__.py
  pastas/extensions/__init__.py
  pastas/extensions/accessor.py
  pastas/model.py
  pastas/plotting/__init__.py
  pastas/plotting/modelcompare.py
  pastas/plotting/modelplots.py
  pastas/plotting/plotly.py
  pastas/plotting/plots.py
  pastas/plotting/plotutil.py
  pastas/stressmodels.py
  pyproject.toml
  tests/test_extension.py
  tests/test_model.py
  tests/test_plots.py
Labels: development

#666 Make replace=True for Model.add_stressmodel
  pastas/model.py
Labels: enhancement

#665 better error message when a class instead of an instance is provided for the rfunc
  pastas/stressmodels.py
Labels: enhancement

#632 Add "good first issue" to contributing docs
  doc/developers/contributing.rst
Labels: documentation, good-first-issue

#668 Add description on normalizing surface water levels
  doc/examples/adding_rivers.ipynb
Labels: documentation

#652 Add pairplot method to visualize correlation between time series
  doc/examples/comparing_models.ipynb
  pastas/plotting/modelcompare.py
  pastas/plotting/modelplots.py
  pastas/plotting/plots.py
  pastas/plotting/plotutil.py
  tests/conftest.py
  tests/test_comparison.py
  tests/test_plots.py
Labels: development

#637 Add map with Pastas models to docs
  doc/conf.py
  doc/index.rst
  doc/map.rst
Labels: documentation

#664 Update Master branch to Pastas 1.3.0
  .github/workflows/ci.yml
  .readthedocs.yaml
  README.rst
  doc/api/index.rst
  doc/conf.py
  doc/developers/contributing.rst
  doc/examples/adding_rivers.ipynb
  doc/examples/adding_trends.ipynb
  doc/examples/adding_wells.ipynb
  doc/examples/changing_responses.ipynb
  doc/examples/comparing_models.ipynb
  doc/examples/example_freq_obs.py
  doc/examples/example_uncertainty.py
  doc/examples/multiple_wells.ipynb
  doc/examples/plotly_interactive_plots.ipynb
  doc/examples/recharge_estimation.ipynb
  doc/examples/standardized_groundwater_index.ipynb
  doc/examples/uncertainty.ipynb
  doc/examples/uncertainty_emcee.ipynb
  doc/index.rst
  doc/map.rst
  doc/userguide/stressmodels.ipynb
  pastas/__init__.py
  pastas/extensions/__init__.py
  pastas/extensions/accessor.py
  pastas/io/base.py
  pastas/model.py
  pastas/noisemodels.py
  pastas/objective_functions.py
  pastas/plotting/__init__.py
  pastas/plotting/modelcompare.py
  pastas/plotting/modelplots.py
  pastas/plotting/plotly.py
  pastas/plotting/plots.py
  pastas/plotting/plotutil.py
  pastas/rcparams.py
  pastas/rfunc.py
  pastas/solver.py
  pastas/stats/signatures.py
  pastas/stressmodels.py
  pastas/timer.py
  pastas/timeseries.py
  pastas/typing/__init__.py
  pastas/typing/types.py
  pastas/version.py
  pyproject.toml
  tests/conftest.py
  tests/test_comparison.py
  tests/test_extension.py
  tests/test_model.py
  tests/test_plots.py
  tests/test_solvers.py
Labels: bug, enhancement, development, deprecation, documentation, code quality
