Repository pastas/pastas, pull requests merged in 2023-01, with the labels that each got.

#445 create Linear instance after instantiation
  pastas/stressmodels.py
Labels: enhancement

#441 Implement Type Hints
  .github/pull_request_template.md
  doc/concepts/armamodel.ipynb
  doc/concepts/noisemodel.ipynb
  doc/examples/02_fix_parameters.ipynb
  doc/examples/example_uncertainty.py
  doc/examples/groundwater_paper/Ex1_simple_model/Example1.ipynb
  pastas/io/base.py
  pastas/io/men.py
  pastas/io/pas.py
  pastas/model.py
  pastas/modelcompare.py
  pastas/modelplots.py
  pastas/modelstats.py
  pastas/noisemodels.py
  pastas/plots.py
  pastas/read/dinoloket.py
  pastas/read/knmi.py
  pastas/read/waterbase.py
  pastas/recharge.py
  pastas/reservoir.py
  pastas/rfunc.py
  pastas/solver.py
  pastas/stats/__init__.py
  pastas/stats/core.py
  pastas/stats/dutch.py
  pastas/stats/metrics.py
  pastas/stats/sgi.py
  pastas/stats/signatures.py
  pastas/stats/tests.py
  pastas/stressmodels.py
  pastas/timer.py
  pastas/timeseries.py
  pastas/transform.py
  pastas/typing/__init__.py
  pastas/typing/types.py
  pastas/utils.py
  requirements.ci.txt
Labels: enhancement

#464 Fix runtime error in ChangeModel
  doc/examples/16_changing_responses.ipynb
  pastas/stressmodels.py
Labels: bug

#465 Have acf return conf instead of stderr
  pastas/modelcompare.py
  pastas/plots.py
  pastas/stats/core.py
Labels: enhancement

#466 Require user-provided response function to be instances
  doc/concepts/armamodel.ipynb
  doc/concepts/handling_timeseries.ipynb
  doc/concepts/noisemodel.ipynb
  doc/concepts/pastas_synthetic.ipynb
  doc/examples/01_basic_model.ipynb
  doc/examples/02_fix_parameters.ipynb
  doc/examples/03_diagnostic_checking.ipynb
  doc/examples/04_adding_rivers.ipynb
  doc/examples/05_adding_wells.ipynb
  doc/examples/06_adding_trends.ipynb
  doc/examples/07_non_linear_recharge.ipynb
  doc/examples/09_calibration_options.ipynb
  doc/examples/10_multiple_wells.ipynb
  doc/examples/11_sgi_example.ipynb
  doc/examples/12_emcee_uncertainty.ipynb
  doc/examples/13_timestep_analysis.ipynb
  doc/examples/14_recharge_estimation.ipynb
  doc/examples/15_uncertainty.ipynb
  doc/examples/16_changing_responses.ipynb
  doc/examples/18_snowmodel.ipynb
  doc/examples/20_signatures.ipynb
  doc/examples/22_comparing_models.ipynb
  doc/examples/example.py
  doc/examples/example_docs.py
  doc/examples/example_snow.py
  doc/examples/example_spline.py
  doc/examples/example_step.py
  doc/examples/example_uncertainty.py
  doc/examples/example_well.py
  doc/examples/groundwater_paper/Ex1_simple_model/Example1.ipynb
  doc/examples/groundwater_paper/Ex2_monitoring_network/Example2.ipynb
  doc/examples/groundwater_paper/Ex_issue_paper/example_issue_pap.ipynb
  pastas/model.py
  pastas/recharge.py
  pastas/stressmodels.py
  tests/test_comparison.py
  tests/test_model.py
  tests/test_plots.py
  tests/test_solvers.py
Labels: enhancement

#467 460 enhancement streamline time series pre processing utilities
  doc/api/index.rst
  doc/concepts/autocorrelation.ipynb
  doc/concepts/hantush_response.ipynb
  doc/examples/00_prepare_timeseries.ipynb
  doc/examples/10_multiple_wells.ipynb
  doc/examples/example_timestep_weighted_resample.py
  pastas/__init__.py
  pastas/io/timeseries_legacy.py
  pastas/model.py
  pastas/modelplots.py
  pastas/stats/dutch.py
  pastas/stats/tests.py
  pastas/stressmodels.py
  pastas/timeseries.py
  pastas/timeseries_utils.py
  pastas/utils.py
  tests/test_notebooks.py
Labels: enhancement

#501 remove menyanthes dump method
  pastas/io/men.py
  pastas/io/men/2.x.g.t (beta).men
  pastas/io/men/3.x.b.c (gamma).men
Labels: deprecation

#494 remove read module
  pastas/__init__.py
  pastas/read/__init__.py
  pastas/read/dinoloket.py
  pastas/read/knmi.py
  pastas/read/menyanthes.py
  pastas/read/waterbase.py
Labels: deprecation

#503 remove deprecated time series and pas-files code
  pastas/io/base.py
  pastas/io/timeseries_legacy.py
  pastas/timeseries.py
  pastas/timeseries_utils.py
Labels: deprecation
