Repository pastas/pastas, pull requests merged in 2024-03, with the labels that each got.

#695 Render equations in docs
  doc/conf.py
Labels: bug, documentation

#693 Add load_dataset method to pastas
  pastas/__init__.py
  pastas/dataset.py
  tests/test_dataset.py
Labels: development

#713 Fix warning Day.delta is deprecated
  pastas/timeseries_utils.py
  tests/test_timeseries_utils.py
Labels: bug, enhancement
