Repository pastas/pastas, pull requests merged in 2024-08, with the labels that each got.

#802 Fix pastas.stats.dutch docstring
  pastas/stats/dutch.py
Labels: documentation

#814 Add brakenhoff 2022 and pastas papers for 2024
  doc/about/publications.rst
  pastas/stressmodels.py
Labels: documentation

#801 Add flexible PastasDeprecationWarning
  pastas/__init__.py
  pastas/decorators.py
  pastas/model.py
  pastas/noisemodels.py
  pastas/plotting/modelplots.py
  pastas/rfunc.py
  tests/test_deprecator.py
  tests/test_plots.py
Labels: enhancement, documentation, code quality

#816 Change .loc to .at where possible
  pastas/model.py
  pastas/noisemodels.py
  pastas/solver.py
  pastas/stats/signatures.py
  pastas/stressmodels.py
  pastas/timeseries.py
  pastas/transform.py
  tests/test_model.py
Labels: enhancement, code quality

#817 Consistent ruff settings in pyproject.toml
  pyproject.toml
Labels: code quality

#813 Increase min_obs for acf for irregular time series to 50
  pastas/stats/core.py
Labels: bug
