Repository pastas/pastas, pull requests merged in 2024-04, with the labels that each got.

#715 Add bokeh plots and deprecate contributions_pie
  doc/examples/interactive_plots.ipynb
  pastas/decorators.py
  pastas/extensions/__init__.py
  pastas/model.py
  pastas/plotting/__init__.py
  pastas/plotting/bokeh.py
  pastas/plotting/modelplots.py
  pastas/plotting/plotly.py
  pyproject.toml
Labels: development

#714 Use istress in responses in result-plot
  pastas/model.py
  pastas/plotting/modelplots.py
  pastas/stressmodels.py
Labels: enhancement

#723 Add "Rise" and "Head" and R2 to plots
  pastas/plotting/modelplots.py
Labels: enhancement

#678 Do not add NoiseModel to Model-class by default anymore
  .github/workflows/python-publish.yml
  doc/benchmarks/armamodel.ipynb
  doc/benchmarks/autocorrelation.ipynb
  doc/benchmarks/check_response_functions.ipynb
  doc/benchmarks/noisemodel.ipynb
  doc/benchmarks/pastas_synthetic.ipynb
  doc/conf.py
  doc/examples/adding_rivers.ipynb
  doc/examples/adding_trends.ipynb
  doc/examples/adding_wells.ipynb
  doc/examples/basic_model.ipynb
  doc/examples/calibration_options.ipynb
  doc/examples/changing_responses.ipynb
  doc/examples/comparing_models.ipynb
  doc/examples/diagnostic_checking.ipynb
  doc/examples/example_freq_obs.py
  doc/examples/example_snow.py
  doc/examples/example_spline.py
  doc/examples/example_step.py
  doc/examples/example_tarso.py
  doc/examples/example_transform.py
  doc/examples/example_uncertainty.py
  doc/examples/example_well.py
  doc/examples/fix_parameters.ipynb
  doc/examples/interactive_plots.ipynb
  doc/examples/modeling_timestep.ipynb
  doc/examples/multiple_wells.ipynb
  doc/examples/non_linear_recharge.ipynb
  doc/examples/prepare_timeseries.ipynb
  doc/examples/recharge_estimation.ipynb
  doc/examples/signatures.ipynb
  doc/examples/snowmodel.ipynb
  doc/examples/standardized_groundwater_index.ipynb
  doc/examples/threshold_non_linear.ipynb
  doc/examples/timestep_analysis.ipynb
  doc/examples/uncertainty.ipynb
  doc/examples/uncertainty_emcee.ipynb
  pastas/__init__.py
  pastas/io/base.py
  pastas/model.py
  pastas/noisemodels.py
  pastas/plotting/modelplots.py
  tests/conftest.py
  tests/test_dataset.py
  tests/test_model.py
  tests/test_solvers.py
Labels: enhancement, development

#734 Update docs for 1.5
  doc/about/courses.rst
  doc/conf.py
  doc/examples/signatures.ipynb
  doc/index.rst
  pastas/stats/signatures.py
Labels: documentation

#731 Update logging messages and raising errors
  doc/developers/code_style.rst
  pastas/decorators.py
  pastas/extensions/accessor.py
  pastas/io/base.py
  pastas/model.py
  pastas/solver.py
  pastas/stats/signatures.py
  pastas/stats/tests.py
  pastas/timeseries.py
  pastas/timeseries_utils.py
  pastas/utils.py
  pastas/version.py
Labels: enhancement, code quality

#743 Readme to markdown
  README.md
  README.rst
Labels: enhancement
