Repository pastas/pastas, pull requests merged in 2024-10, with the labels that each got.

#831 Run uncertainty estimation benchmark notebook with multiprocessing
  doc/benchmarks/armamodel.ipynb
  doc/benchmarks/check_response_functions.ipynb
  doc/benchmarks/index.rst
  doc/benchmarks/noisemodel.ipynb
  doc/benchmarks/pastas_synthetic.ipynb
  doc/benchmarks/pastas_uncertainty_benchmark.ipynb
  pastas/version.py
Labels: enhancement, documentation

#828 Add contributions plot with optional stress time series and response
  pastas/plotting/modelplots.py
  tests/test_plots.py
Labels: development

#833 Load parameter bounds and vary if changed in pas file
  pastas/io/base.py
Labels: bug

#835 Remove capture of warnings in logger
  pastas/stats/metrics.py
Labels: bug, deprecation

#836 Update the Pastas readthedocs quick example
  doc/_static/example_output.png
  doc/index.rst
Labels: documentation
