Repository pastas/pastas, pull requests merged in 2025-01, with the labels that each got.

#841 Fix typos
  .github/workflows/code_spell.yml
  .github/workflows/test_format_lint.yml
  doc/benchmarks/pastas_synthetic.ipynb
  doc/benchmarks/pastas_uncertainty_benchmark.ipynb
  doc/examples/adding_rivers.ipynb
  doc/examples/adding_trends.ipynb
  doc/examples/basic_model.ipynb
  doc/examples/calibration_options.ipynb
  doc/examples/data/B28H1808_2_pastas-0-22-0.pas
  doc/examples/data/B28H1808_2_pastas-0-23-0.pas
  doc/examples/diagnostic_checking.ipynb
  doc/examples/fix_parameters.ipynb
  doc/examples/groundwater_paper/Ex1_simple_model/Example1.ipynb
  doc/examples/multiple_wells.ipynb
  doc/examples/prepare_timeseries.ipynb
  doc/examples/snowmodel.ipynb
  doc/examples/threshold_non_linear.ipynb
  doc/userguide/pastas_modeling.ipynb
  doc/userguide/response_functions.ipynb
  doc/userguide/stressmodels.ipynb
  pastas/io/base.py
  pastas/model.py
  pastas/plotting/modelcompare.py
  pastas/plotting/plotly.py
  pastas/stats/core.py
  pastas/stats/tests.py
  pastas/timeseries_utils.py
  pyproject.toml
Labels: documentation, code quality

#829 Add model check functionality
  pastas/__init__.py
  pastas/check.py
  pastas/plotting/plotutil.py
  tests/conftest.py
  tests/test_checks.py
Labels: development

#856 remove constraints for numba rc and py313
  pyproject.toml
Labels: code quality
