Repository pastas/pastas, pull requests merged in 2025-03, with the labels that each got.

#913 Update issue templates (part 2)
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/bug_form.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature.md
  .github/ISSUE_TEMPLATE/task.md
Labels: documentation

#911 Add normalized Nash-Sutcliffe Efficiency
  pastas/modelstats.py
  pastas/stats/metrics.py
  tests/test_metrics.py
Labels: enhancement

#896 Improve the CCF/ACF function and make it more robust by using gaussian kernels by default
  pastas/plotting/plots.py
  pastas/stats/core.py
Labels: bug, enhancement

#903 Update EmceeSolver class and Likelihood functions
  doc/examples/index.rst
  doc/examples/uncertainty_emcee.ipynb
  doc/examples/uncertainty_ls_mcmc.ipynb
  pastas/objective_functions.py
  pastas/solver.py
Labels: bug

#920 Correct description of low_pulse_count signature
  pastas/plotting/plots.py
  pastas/stats/core.py
  pastas/stats/signatures.py
Labels: documentation

#918 CCF improvements
  pastas/decorators.py
  pastas/stats/core.py
Labels: bug, enhancement

#924 add warning for response > warmup to fit_report
  pastas/model.py
  tests/test_model.py
Labels: enhancement

#923 avoid empty column in `ml.plotly.results()` if stderr=False
  pastas/plotting/plotly.py
Labels: bug

#926 Fix Potential File Descriptor Leaks
  pastas/io/pas.py
  tests/test_examples.py
Labels: bug, code quality

#927 add docstring to ml.stats.diagnostics
  pastas/modelstats.py
Labels: documentation
