Repository pastas/pastas, pull requests merged in 2025-02, with the labels that each got.

#878 Add ruff commands to development section of docs
  doc/developers/code_style.rst
Labels: documentation

#876 Do not compute RMSN when no noise model is present in the model
  pastas/modelstats.py
  tests/conftest.py
  tests/test_model.py
Labels: enhancement

#895 894 update unit tests fixtures
  tests/conftest.py
  tests/test_examples.py
  tests/test_metrics.py
  tests/test_model.py
  tests/test_notebooks.py
  tests/test_notebooks_bench.py
  tests/test_plots.py
  tests/test_recharge.py
Labels: code quality

#901 Add stderr to results plots in Bokeh and Plotly
  pastas/plotting/bokeh.py
  pastas/plotting/plotly.py
Labels: enhancement

#900 Fix bug where interactive Bokeh plots did not work without noise model.
  pastas/plotting/bokeh.py
Labels: bug

#904 allow errors in signatures.summary
  pastas/stats/signatures.py
Labels: enhancement
