Repository pastas/pastas, pull requests merged in 2025-08, with the labels that each got.

#966 Log signature name
  pastas/stats/signatures.py
Labels: code quality

#967 Fix NumPy version higher than 2.0
  LICENSE
  pyproject.toml
  tests/regression.py
Labels: bug

#983 Revisit testing routine
  .github/workflows/code_spell.yml
  .github/workflows/test_spelling.yml
  .github/workflows/test_urls.py
  .github/workflows/test_urls.yml
  doc/examples/stowa_assessment.ipynb
  doc/examples/stowa_cases_contribution_assessment.ipynb
  doc/examples/stowa_model_structure.ipynb
  doc/examples/stowa_preprocessing.ipynb
  pyproject.toml
Labels: code quality

#945 Add forecast module to Pastas
  .gitignore
  doc/examples/data_forecast/ensemble_evap.csv
  doc/examples/data_forecast/ensemble_prec.csv
  doc/examples/data_forecast/ensemble_temp.csv
  doc/examples/data_forecast/evap.csv
  doc/examples/data_forecast/heads.csv
  doc/examples/data_forecast/prec.csv
  doc/examples/data_forecast/temp.csv
  doc/examples/ensemble_predictions.ipynb
  doc/examples/index.rst
  pastas/__init__.py
  pastas/forecast.py
  pastas/plotting/plotutil.py
  tests/test_forecast.py
Labels: enhancement
